### ISSUE TITLE
migrate to mcvine convention

### ISSUE THREAD

**Issue by yxqd** [mcvine/SCADGen#7]
## Introduction

We will need to migrate SCADgen to support mcvine convention. The pyre convention and the mcvine convention is very similar, but the pyre convention is more generic and a bit simpler, while the mcvine convention is more specific to the instrument simulation. Here is an example xml code:

```
<?xml version="1.0"?>
<!DOCTYPE geometry>

<geometry>

    <difference>
        <sphere radius="3.*cm"/>
        <intersection>
            <rotation>
                <translation>
                    <union>
                        <cylinder height="5.*cm" radius="1.*cm"/>
                        <sphere radius="2.*cm"/>
                        <block thickness="1.*mm" width="5*cm" height="4.*cm" />
                    </union>
                    <vector beam="0.*m" transversal="0.*m" vertical="0.2*cm" />
                </translation>
                <angle>90*deg</angle>
                <axis beam="0.0" transversal="0.0" vertical="1.0" />
            </rotation>
            <pyramid thickness="1.*cm" width="4.*cm" height="2.*cm"/>
        </intersection>
    </difference>

</geometry>
```

One main difference is that in mcvine convention, the dimensions are in terms of three directions
* beam (horizontal, along the forward beam direction)
* transversal (horizontal, perpendicular to beam)
* vertical

If we call beam direction _x_, transversal _y_, vertical _z_, then _x_, _y_, _z_ form a right-hand coordinate system.

Another important difference is that the physical units are presented in the xml files such as "cm" and "degree". These physical quantities can be converted to pure numbers by following a procedure similar to this:
```
import pyre.units
parser = pyre.units.parser()
# suppose "s" is a string variable for a length quantity like width, e.g., "3*cm"
# and you want to convert the number to be in terms of millimeters
mm = parser.parse('mm')
print parser.parse(s)/mm
```
BTW, pyre can be installed by `conda install -c mcvine pyre`

## TODO

Some primitives and operations need changes on attributes:

* [x] Block: diagonal -> thickness, width, height
* [x] Pyramid: edgeX, edgeY, height -> thickness, width, height
* [x] Translation: vector-> beam, transversal, vertical
* [x] Rotation: axis -> beam, transversal, vertical

Others only need to handle units:
* [x] Sphere
* [x] Cylinder

**Comment by yxqd** [comment]
@ilumsden @granrothge

**Comment by granrothge** [comment]
The union still does not work.

```<!DOCTYPE geometry>

<geometry>
    <difference>
        <cylinder height="50" radius="55.0"/>
        <union>
            <translation>
                <union>
                    <rotation>
                        <rotation>
                            <pyramid edgeX="10" edgeY="10" height="55.0"/>
                            <angle>90</angle>
                            <vector>(0,1,0)</vector>
                        </rotation>
                        <angle>30</angle>
                        <vector>(0,0,1)</vector>
                    </rotation>
                    <rotation>
                          <rotation>
                              <pyramid edgeX="10" edgeY="10" height="55.0"/>
                              <angle>90</angle>
                              <vector>(0,1,0)</vector>
                          </rotation>
                          <angle>15</angle>
                          <vector>(0,0,1)</vector>
                    </rotation>
                    <rotation>
                          <rotation>
                              <pyramid edgeX="10" edgeY="10" height="55.0"/>
                              <angle>90</angle>
                              <vector>(0,1,0)</vector>
                          </rotation>
                          <angle>45</angle>
                          <vector>(0,0,1)</vector>
                    </rotation>

                </union>
                <vector>(0,0,25)</vector>
            </translation>
            <union>
                <cylinder height="70" radius="25.0"/>
                <translation>
                    <block height="110" width="110" thickness="110"/>
                    <vector>(0,-55,0)</vector>
                </translation>
            </union>
        </union>
   </difference>
</geometry>```

**Comment by ilumsden** [comment]
@yxqd is the XML syntax for translate in MCViNE the same as in pyre?

**Comment by ilumsden** [comment]
Also, I added unit handling to torus as well.

**Comment by yxqd** [comment]
@ilumsden The XML syntax is basically the same. Please see the example xml code at the top.

**Comment by ilumsden** [comment]
Oh, sorry. I didn't notice that there was a translation operator there.

**Comment by yxqd** [comment]
BTW, please commit and push your revisions often so that it is easier to merge our revisions

**Comment by ilumsden** [comment]
OK. Just so you know, I've almost finished with the revisions for this issue and #6

**Comment by yxqd** [comment]
Thanks @ilumsden !

**Comment by ilumsden** [comment]
However, I have found a bit of an issue. Since we are now using the `unit_parser` from pyre, this repo will have to be restricted to Python 2.7 right now because the conda build of pyre only supports Python 2.7

**Comment by ilumsden** [comment]
All the code I've been writing should support Python 2.7 and Python 3.3+, so this isn't an immediate problem.

**Comment by yxqd** [comment]
I see. That is fine for now I think.

**Comment by yxqd** [comment]
I made some changes to the branch. Could you please do

`$ git pull origin migrate-to-mcvine`

and see if it merge with your local branch well?

**Comment by yxqd** [comment]
That branch seems to be working for @granrothge 's xml file

![collimator](https://user-images.githubusercontent.com/1796155/37797489-5a1e5250-2df0-11e8-950f-b6b4d64d30de.png)

**Comment by ilumsden** [comment]
I just finished implementing all the changes from this issue and #6. After I test the test XMLs to make sure the correct code is generated, I'll open a pull request.

**Comment by yxqd** [comment]
Great! Thanks.

**Comment by ilumsden** [comment]
I found an interesting bug in the code. Apparently, for any piece of data that is passed through one of the `_convert` lambdas, the data must have units. If it doesn't, the code adds `*m**-1` in the SCAD code, which causes issues in OpenSCAD.
